services:
  postgres:
    image: postgres:16
    container_name: novalake-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-novalake}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-novalake_local_password}
      POSTGRES_DB: ${POSTGRES_DB:-novalake_ops}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/postgres_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novalake -d novalake_ops"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    build:
      context: ..
      dockerfile: infra/spark/Dockerfile
    image: novalake/spark-iceberg:3.5.1
    container_name: novalake-spark-master
    environment:
      PYTHONPATH: /opt/novalake
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master",
        "--host",
        "spark-master",
        "--port",
        "7077",
        "--webui-port",
        "8080"
      ]
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../:/opt/novalake
    working_dir: /opt/novalake

  spark-worker:
    image: novalake/spark-iceberg:3.5.1
    container_name: novalake-spark-worker
    depends_on:
      - spark-master
    environment:
      PYTHONPATH: /opt/novalake
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077",
        "--webui-port",
        "8081"
      ]
    ports:
      - "8081:8081"
    volumes:
      - ../:/opt/novalake
    working_dir: /opt/novalake

  notebook-lab:
    build:
      context: ..
      dockerfile: infra/lab/Dockerfile
    image: novalake/notebook-lab:3.5.1
    container_name: novalake-notebook-lab
    profiles: ["lab"]
    depends_on:
      - spark-master
      - spark-worker
    environment:
      PYTHONPATH: /opt/novalake
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
      PYSPARK_SUBMIT_ARGS: >-
        --master spark://spark-master:7077
        --conf spark.sql.catalogImplementation=in-memory
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
        --conf spark.sql.catalog.novalake=org.apache.iceberg.spark.SparkCatalog
        --conf spark.sql.catalog.novalake.type=hadoop
        --conf spark.sql.catalog.novalake.warehouse=/opt/novalake/data/warehouse
        pyspark-shell
    ports:
      - "8888:8888"
    volumes:
      - ../:/opt/novalake
    working_dir: /opt/novalake

volumes:
  postgres_data:
